server:
  use-forward-headers : true
  port: 8080
  nm: sample
  servlet:
    session:
      timeout: 30m
      cookie:
        name: APPSESSIONID91
  tomcat:
    max-http-form-post-size: 10MB

spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://dev.openmate.com:15432/ilpes18?stringtype=unspecified
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ilpes18
    password: openmate1!
    hikari:
      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 1
      validation-timeout: 250
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
 
            
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.openmate.sample.util.openMap
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    callSettersOnNulls: true
    